"""empty message

Revision ID: 00c9b476c611
Revises: d4bad94d0626
Create Date: 2019-04-12 13:51:28.366960

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '00c9b476c611'
down_revision = 'd4bad94d0626'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('RepoStructures', sa.Column('RepoUrl', sa.Text(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('RepoStructures', 'RepoUrl')
    # ### end Alembic commands ###
