"""empty message

Revision ID: 3ac5aea9cdff
Revises: 86a9d56883b9
Create Date: 2019-04-05 01:41:27.182538

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3ac5aea9cdff'
down_revision = '86a9d56883b9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('SubjectExperts', sa.Column('Score', sa.Integer(), nullable=False))
    op.drop_column('SubjectExperts', 'score')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('SubjectExperts', sa.Column('score', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('SubjectExperts', 'Score')
    # ### end Alembic commands ###
