"""empty message

Revision ID: 65f94c3bb1cf
Revises: 09d49d07d281
Create Date: 2019-04-07 15:11:51.104082

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '65f94c3bb1cf'
down_revision = '09d49d07d281'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('RepoStructures',
    sa.Column('RepoId', sa.BigInteger(), nullable=False),
    sa.Column('RepoName', sa.Text(), nullable=False),
    sa.Column('RepoUrl', sa.Text(), nullable=False),
    sa.Column('RepoTree', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['RepoId'], ['Repos.RepoId'], ),
    sa.PrimaryKeyConstraint('RepoId')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('RepoStructures')
    # ### end Alembic commands ###
