"""empty message

Revision ID: 7fb0697d7c2a
Revises: 9b6f0bddbca1
Create Date: 2019-04-05 01:13:49.888584

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7fb0697d7c2a'
down_revision = '9b6f0bddbca1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Repos',
    sa.Column('RepoId', sa.BigInteger(), nullable=False),
    sa.Column('RepoName', sa.Text(), nullable=False),
    sa.Column('RepoUrl', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('RepoId')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Repos')
    # ### end Alembic commands ###
