"""empty message

Revision ID: 9b6f0bddbca1
Revises: 
Create Date: 2019-04-05 00:41:50.674792

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9b6f0bddbca1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Authors',
    sa.Column('AuthorId', sa.BigInteger(), nullable=False),
    sa.Column('AuthorName', sa.Text(), nullable=True),
    sa.Column('AuthorEmail', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('AuthorId')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Authors')
    # ### end Alembic commands ###
