"""empty message

Revision ID: d4bad94d0626
Revises: 65f94c3bb1cf
Create Date: 2019-04-12 12:58:02.685259

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd4bad94d0626'
down_revision = '65f94c3bb1cf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('BugProbabilities',
    sa.Column('FileId', sa.BigInteger(), nullable=False),
    sa.Column('NoOfTimeChanged', sa.Integer(), nullable=True),
    sa.Column('BuggyCommits', sa.Integer(), nullable=True),
    sa.Column('BuggyCommitsPercentage', postgresql.DOUBLE_PRECISION(), nullable=True),
    sa.ForeignKeyConstraint(['FileId'], ['Files.FileId'], ),
    sa.PrimaryKeyConstraint('FileId')
    )
    op.drop_table('BugProbablities')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('BugProbablities',
    sa.Column('FileId', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('NoOfTimeChanged', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('BuggyCommits', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('BuggyCommitsPercentage', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['FileId'], ['Files.FileId'], name='BugProbablities_FileId_fkey'),
    sa.PrimaryKeyConstraint('FileId', name='BugProbablities_pkey')
    )
    op.drop_table('BugProbabilities')
    # ### end Alembic commands ###
