"""empty message

Revision ID: 09d49d07d281
Revises: faf24f5745ac
Create Date: 2019-04-05 01:51:36.570593

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '09d49d07d281'
down_revision = 'faf24f5745ac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('BugProbablities',
    sa.Column('FileId', sa.BigInteger(), nullable=False),
    sa.Column('NoOfTimeChanged', sa.Integer(), nullable=True),
    sa.Column('BuggyCommits', sa.Integer(), nullable=True),
    sa.Column('BuggyCommitsPercentage', postgresql.DOUBLE_PRECISION(), nullable=True),
    sa.ForeignKeyConstraint(['FileId'], ['Files.FileId'], ),
    sa.PrimaryKeyConstraint('FileId')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('BugProbablities')
    # ### end Alembic commands ###
