"""empty message

Revision ID: 9701a1860e6a
Revises: 7fb0697d7c2a
Create Date: 2019-04-05 01:24:53.952405

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9701a1860e6a'
down_revision = '7fb0697d7c2a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Files',
    sa.Column('FileId', sa.BigInteger(), nullable=False),
    sa.Column('RepoId', sa.Integer(), nullable=True),
    sa.Column('FileName', sa.Text(), nullable=False),
    sa.Column('FilePath', sa.Text(), nullable=False),
    sa.Column('FileType', sa.Text(), nullable=False),
    sa.Column('FileSizeBytes', sa.BigInteger(), nullable=False),
    sa.Column('LinesOfCode', sa.Integer(), nullable=False),
    sa.Column('LastModified', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['RepoId'], ['Repos.RepoId'], ),
    sa.PrimaryKeyConstraint('FileId')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Files')
    # ### end Alembic commands ###
