"""empty message

Revision ID: faf24f5745ac
Revises: 3ac5aea9cdff
Create Date: 2019-04-05 01:49:08.707740

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'faf24f5745ac'
down_revision = '3ac5aea9cdff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('FileDependencies',
    sa.Column('SourceFileId', sa.BigInteger(), nullable=False),
    sa.Column('DestinationFileId', sa.BigInteger(), nullable=False),
    sa.Column('NoOfTimeChanged', sa.Integer(), nullable=False),
    sa.Column('NormalizedChanged', postgresql.DOUBLE_PRECISION(), nullable=False),
    sa.ForeignKeyConstraint(['DestinationFileId'], ['Files.FileId'], ),
    sa.ForeignKeyConstraint(['SourceFileId'], ['Files.FileId'], ),
    sa.PrimaryKeyConstraint('SourceFileId', 'DestinationFileId')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('FileDependencies')
    # ### end Alembic commands ###
